server:
  port: 8080

spring:
  application:
    name: EDUMATE_Backend Server
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/edumate}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:hgl03}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:

      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
  thymeleaf:
    prefix: classpath:/templates/email/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false



system:
  server-link: http://localhost:8080
  default:
    email:
      from: edumate.working@gmail.com
      name: Edumate
    admin:
      account:
        username: Edumate System Admin
        email: admin@gmail.com
        password: 12345678
  exception:
    show:
      client-info: false
  security:
    jwt:
      access:
        expiration-hour: 8
      refresh:
        expiration-day: 14
      secretAccessKey: f6d0a6c1b856198768038df5da8cf5ba16176f1a34006cd4e88addaef0448b48
      secretRefreshKey: RdzQtkYMquhS24sAcwUJyPk9z7Q10o8IeCCTwbZFAS4=
  firebase:
    config:
      path: firebase/firebase-admin-service-account.json

  cloudinary:
    cloud_name: dyawg2wm1
    api_key: 312721116553145
    api_secret: qMNWZd-5kKoa-tEZbrkH6HSYepY

  gcloud-project:
    id: edumate-458118
    region: us-central1
    model: gemini-2.0-flash




